name: "Maven Test"

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - pom.xml

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ hashFiles('pom.xml') }}

      - run: mvn test

  package:
    name: Package and Upload
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - run: mvn package -DskipTests

      - uses: actions/upload-artifact@v2
        with:
          name: demo.jar
          path: target/demo-*.jar
